samples:
  'EL-012': ancient/muskoxmap/EL012.merged.rmdup.merged.realn.bam
  'AH-1_40': mapping2/results/MQ30bam/AH-1_40.MQ30.bam
  'AI-1_119': mapping2/results/MQ30bam/AI-1_119.MQ30.bam
  'BI-1_162': mapping2/results/MQ30bam/BI-1_162.MQ30.bam
  'BI-26_18': mapping2/results/MQ30bam/BI-26_18.MQ30.bam
  'BI-28_99': mapping2/results/MQ30bam/BI-28_99.MQ30.bam
  'BI-30_167': mapping2/results/MQ30bam/BI-30_167.MQ30.bam
  'BI-31_168': mapping2/results/MQ30bam/BI-31_168.MQ30.bam
  'BI-32_19': mapping2/results/MQ30bam/BI-32_19.MQ30.bam
  'BI-33_169': mapping2/results/MQ30bam/BI-33_169.MQ30.bam
  'BI-35_20': mapping2/results/MQ30bam/BI-35_20.MQ30.bam
  'BI-36_21': mapping2/results/MQ30bam/BI-36_21.MQ30.bam
  'BI-37_170': mapping2/results/MQ30bam/BI-37_170.MQ30.bam
  'BL-10_175': mapping2/results/MQ30bam/BL-10_175.MQ30.bam
  'BL-11_9': mapping2/results/MQ30bam/BL-11_9.MQ30.bam
  'BL-13_8': mapping2/results/MQ30bam/BL-13_8.MQ30.bam
  'BL-14_176': mapping2/results/MQ30bam/BL-14_176.MQ30.bam
  'BL-15_31': mapping2/results/MQ30bam/BL-15_31.MQ30.bam
  'BL-17_11': mapping2/results/MQ30bam/BL-17_11.MQ30.bam
  'BL-1_7': mapping2/results/MQ30bam/BL-1_7.MQ30.bam
  'BL-20_10': mapping2/results/MQ30bam/BL-20_10.MQ30.bam
  'BL-2_26': mapping2/results/MQ30bam/BL-2_26.MQ30.bam
  'BL-23_32': mapping2/results/MQ30bam/BL-23_32.MQ30.bam
  'BL-24_33': mapping2/results/MQ30bam/BL-24_33.MQ30.bam
  'BL-4_28': mapping2/results/MQ30bam/BL-4_28.MQ30.bam
  'BL-6_29': mapping2/results/MQ30bam/BL-6_29.MQ30.bam
  'CH-3_62': mapping2/results/MQ30bam/CH-3_62.MQ30.bam
  'CH-5_137': mapping2/results/MQ30bam/CH-5_137.MQ30.bam
  'CH-7_45': mapping2/results/MQ30bam/CH-7_45.MQ30.bam
  'CI-5_156': mapping2/results/MQ30bam/CI-5_156.MQ30.bam
  'CI-8_14': mapping2/results/MQ30bam/CI-8_14.MQ30.bam
  'CM-1_61': mapping2/results/MQ30bam/CM-1_61.MQ30.bam
  'CM-2_63': mapping2/results/MQ30bam/CM-2_63.MQ30.bam
  'DI-16_74': mapping2/results/MQ30bam/DI-16_74.MQ30.bam
  'DI-5_171': mapping2/results/MQ30bam/DI-5_171.MQ30.bam
  'EI-23_12': mapping2/results/MQ30bam/EI-23_12.MQ30.bam
  'EI-28_17': mapping2/results/MQ30bam/EI-28_17.MQ30.bam
  'EU-1_145': mapping2/results/MQ30bam/EU-1_145.MQ30.bam
  'EU-12_148': mapping2/results/MQ30bam/EU-12_148.MQ30.bam
  'EU-15_150': mapping2/results/MQ30bam/EU-15_150.MQ30.bam
  'EU-7_67': mapping2/results/MQ30bam/EU-7_67.MQ30.bam
  'FR-2_39': mapping2/results/MQ30bam/FR-2_39.MQ30.bam
  'GF-19_117': mapping2/results/MQ30bam/GF-19_117.MQ30.bam
  'GF-2_75': mapping2/results/MQ30bam/GF-2_75.MQ30.bam
  'GF-5_71': mapping2/results/MQ30bam/GF-5_71.MQ30.bam
  'HD-1': mapping2/results/MQ30bam/HD-1.MQ30.bam
  'HD-2': mapping2/results/MQ30bam/HD-2.MQ30.bam
  'HD-3': mapping2/results/MQ30bam/HD-3.MQ30.bam
  'HD-5': mapping2/results/MQ30bam/HD-5.MQ30.bam
  'JA-1_34': mapping2/results/MQ30bam/JA-1_34.MQ30.bam
  'JA-2_35': mapping2/results/MQ30bam/JA-2_35.MQ30.bam
  'JA-4_36': mapping2/results/MQ30bam/JA-4_36.MQ30.bam
  'KU-11_64': mapping2/results/MQ30bam/KU-11_64.MQ30.bam
  'KU-12_70': mapping2/results/MQ30bam/KU-12_70.MQ30.bam
  'KU-13_38': mapping2/results/MQ30bam/KU-13_38.MQ30.bam
  'KU-16_77': mapping2/results/MQ30bam/KU-16_77.MQ30.bam
  'KU-18_1': mapping2/results/MQ30bam/KU-18_1.MQ30.bam
  'KU-21_43': mapping2/results/MQ30bam/KU-21_43.MQ30.bam
  'KU-23_3': mapping2/results/MQ30bam/KU-23_3.MQ30.bam
  'KU-25_4': mapping2/results/MQ30bam/KU-25_4.MQ30.bam
  'KU-2_57': mapping2/results/MQ30bam/KU-2_57.MQ30.bam
  'KU-27_2': mapping2/results/MQ30bam/KU-27_2.MQ30.bam
  'KU-31_46': mapping2/results/MQ30bam/KU-31_46.MQ30.bam
  'KU-32_48': mapping2/results/MQ30bam/KU-32_48.MQ30.bam
  'KU-33_52': mapping2/results/MQ30bam/KU-33_52.MQ30.bam
  'KU-39_56': mapping2/results/MQ30bam/KU-39_56.MQ30.bam
  'KU-4_72': mapping2/results/MQ30bam/KU-4_72.MQ30.bam
  'MO25_ZA': mapping2/results/MQ30bam/MO25_ZA.MQ30.bam
  'MO28_ZA': mapping2/results/MQ30bam/MO28_ZA.MQ30.bam
  'MO29_ZA': mapping2/results/MQ30bam/MO29_ZA.MQ30.bam
  'MO32_ZA': mapping2/results/MQ30bam/MO32_ZA.MQ30.bam
  'MO33_ZA': mapping2/results/MQ30bam/MO33_ZA.MQ30.bam
  'MO34_ZA': mapping2/results/MQ30bam/MO34_ZA.MQ30.bam
  'MO35_ZA': mapping2/results/MQ30bam/MO35_ZA.MQ30.bam
  'MO41_ZA': mapping2/results/MQ30bam/MO41_ZA.MQ30.bam
  'MO42_ZA': mapping2/results/MQ30bam/MO42_ZA.MQ30.bam
  'MO43_ZA': mapping2/results/MQ30bam/MO43_ZA.MQ30.bam
  'MO44_ZA': mapping2/results/MQ30bam/MO44_ZA.MQ30.bam
  'MO45_ZA': mapping2/results/MQ30bam/MO45_ZA.MQ30.bam
  'MO46_ZA': mapping2/results/MQ30bam/MO46_ZA.MQ30.bam
  'MO48_ZA': mapping2/results/MQ30bam/MO48_ZA.MQ30.bam
  'MO49_ZA': mapping2/results/MQ30bam/MO49_ZA.MQ30.bam
  'MO50_ZA': mapping2/results/MQ30bam/MO50_ZA.MQ30.bam
  'RY-3': mapping2/results/MQ30bam/RY-3.MQ30.bam
  'SF-1_42': mapping2/results/MQ30bam/SF-1_42.MQ30.bam
  'SF-3_49': mapping2/results/MQ30bam/SF-3_49.MQ30.bam
  'TH-27_69': mapping2/results/MQ30bam/TH-27_69.MQ30.bam
