depths:
  'EL-012':
    - 8
    - 26
  'AH-1_40':
    - 8
    - 22
  'AI-1_119':
    - 8
    - 26
  'BI-1_162':
    - 8
    - 20
  'BI-26_18':
    - 8
    - 21
  'BI-28_99':
    - 8
    - 24
  'BI-35_20':
    - 8
    - 25
  'BI-36_21':
    - 8
    - 25
  'BL-10_175':
    - 4
    - 25
  'BL-11_9':
    - 8
    - 28
  'BL-13_8':
    - 8
    - 25
  'BL-15_31':
    - 8
    - 20
  'BL-17_11':
    - 8
    - 23
  'BL-1_7':
    - 8
    - 19
  'BL-20_10':
    - 8
    - 28
  'BL-2_26':
    - 8
    - 22
  'BL-23_32':
    - 8
    - 21
  'BL-24_33':
    - 8
    - 29
  'BL-4_28':
    - 8
    - 21
  'BL-6_29':
    - 8
    - 23
  'CH-3_62':
    - 8
    - 20
  'CH-7_45':
    - 8
    - 28
  'CI-8_14':
    - 8
    - 23
  'CM-1_61':
    - 8
    - 24
  'CM-2_63':
    - 8
    - 25
  'EI-23_12':
    - 8
    - 20
  'EI-28_17':
    - 8
    - 21
  'EU-7_67':
    - 8
    - 21
  'HD-1':
    - 8
    - 30
  'HD-2':
    - 8
    - 33
  'HD-5':
    - 8
    - 53
  'JA-1_34':
    - 8
    - 20
  'JA-4_36':
    - 8
    - 19
  'KU-11_64':
    - 8
    - 22
  'KU-12_70':
    - 8
    - 20
  'KU-13_38':
    - 8
    - 23
  'KU-21_43':
    - 8
    - 19
  'KU-23_3':
    - 8
    - 22
  'KU-2_57':
    - 8
    - 20
  'KU-27_2':
    - 8
    - 21
  'KU-31_46':
    - 8
    - 19
  'KU-32_48':
    - 8
    - 21
  'KU-39_56':
    - 8
    - 23
  'KU-4_72':
    - 8
    - 21
  'MO25_ZA':
    - 8
    - 22
  'MO28_ZA':
    - 8
    - 22
  'MO29_ZA':
    - 8
    - 20
  'MO32_ZA':
    - 8
    - 20
  'MO33_ZA':
    - 8
    - 21
  'MO34_ZA':
    - 8
    - 25
  'MO35_ZA':
    - 8
    - 23
  'MO42_ZA':
    - 8
    - 20
  'MO46_ZA':
    - 8
    - 20
  'MO49_ZA':
    - 8
    - 20
  'MO50_ZA':
    - 8
    - 25
  'RY-3':
    - 8
    - 23
  'SF-1_42':
    - 8
    - 26
  'SF-3_49':
    - 8
    - 22
  'TH-27_69':
    - 8
    - 20
samples:
  'EL-012': ancient/muskoxmap/EL012.merged.rmdup.merged.realn.bam
  'AH-1_40': MQ30bam/AH-1_40.MQ30.bam
  'AI-1_119': MQ30bam/AI-1_119.MQ30.bam
  'BI-1_162': MQ30bam/BI-1_162.MQ30.bam
  'BI-26_18': MQ30bam/BI-26_18.MQ30.bam
  'BI-28_99': MQ30bam/BI-28_99.MQ30.bam
  'BI-35_20': MQ30bam/BI-35_20.MQ30.bam
  'BI-36_21': MQ30bam/BI-36_21.MQ30.bam
  'BL-10_175': MQ30bam/BL-10_175.MQ30.bam
  'BL-11_9': MQ30bam/BL-11_9.MQ30.bam
  'BL-13_8': MQ30bam/BL-13_8.MQ30.bam
  'BL-15_31': MQ30bam/BL-15_31.MQ30.bam
  'BL-17_11': MQ30bam/BL-17_11.MQ30.bam
  'BL-1_7': MQ30bam/BL-1_7.MQ30.bam
  'BL-20_10': MQ30bam/BL-20_10.MQ30.bam
  'BL-2_26': MQ30bam/BL-2_26.MQ30.bam
  'BL-23_32': MQ30bam/BL-23_32.MQ30.bam
  'BL-24_33': MQ30bam/BL-24_33.MQ30.bam
  'BL-4_28': MQ30bam/BL-4_28.MQ30.bam
  'BL-6_29': MQ30bam/BL-6_29.MQ30.bam
  'CH-3_62': MQ30bam/CH-3_62.MQ30.bam
  'CH-7_45': MQ30bam/CH-7_45.MQ30.bam
  'CI-8_14': MQ30bam/CI-8_14.MQ30.bam
  'CM-1_61': MQ30bam/CM-1_61.MQ30.bam
  'CM-2_63': MQ30bam/CM-2_63.MQ30.bam
  'EI-23_12': MQ30bam/EI-23_12.MQ30.bam
  'EI-28_17': MQ30bam/EI-28_17.MQ30.bam
  'EU-7_67': MQ30bam/EU-7_67.MQ30.bam
  'HD-1': MQ30bam/HD-1.MQ30.bam
  'HD-2': MQ30bam/HD-2.MQ30.bam
  'HD-5': MQ30bam/HD-5.MQ30.bam
  'JA-1_34': MQ30bam/JA-1_34.MQ30.bam
  'JA-4_36': MQ30bam/JA-4_36.MQ30.bam
  'KU-11_64': MQ30bam/KU-11_64.MQ30.bam
  'KU-12_70': MQ30bam/KU-12_70.MQ30.bam
  'KU-13_38': MQ30bam/KU-13_38.MQ30.bam
  'KU-21_43': MQ30bam/KU-21_43.MQ30.bam
  'KU-23_3': MQ30bam/KU-23_3.MQ30.bam
  'KU-2_57': MQ30bam/KU-2_57.MQ30.bam
  'KU-27_2': MQ30bam/KU-27_2.MQ30.bam
  'KU-32_48': MQ30bam/KU-32_48.MQ30.bam
  'KU-31_46': MQ30bam/KU-31_46.MQ30.bam
  'KU-39_56': MQ30bam/KU-39_56.MQ30.bam
  'KU-4_72': MQ30bam/KU-4_72.MQ30.bam
  'MO25_ZA': MQ30bam/MO25_ZA.MQ30.bam
  'MO28_ZA': MQ30bam/MO28_ZA.MQ30.bam
  'MO29_ZA': MQ30bam/MO29_ZA.MQ30.bam
  'MO32_ZA': MQ30bam/MO32_ZA.MQ30.bam
  'MO33_ZA': MQ30bam/MO33_ZA.MQ30.bam
  'MO34_ZA': MQ30bam/MO34_ZA.MQ30.bam
  'MO35_ZA': MQ30bam/MO35_ZA.MQ30.bam
  'MO42_ZA': MQ30bam/MO42_ZA.MQ30.bam
  'MO46_ZA': MQ30bam/MO46_ZA.MQ30.bam
  'MO49_ZA': MQ30bam/MO49_ZA.MQ30.bam
  'MO50_ZA': MQ30bam/MO50_ZA.MQ30.bam
  'RY-3': MQ30bam/RY-3.MQ30.bam
  'SF-1_42': MQ30bam/SF-1_42.MQ30.bam
  'SF-3_49': MQ30bam/SF-3_49.MQ30.bam
  'TH-27_69': MQ30bam/TH-27_69.MQ30.bam
